[package]
name = "custom-protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
toml = "0.8.10"
serde = { version = "1.0.197", features = ["derive"] }
ipnet = "2.9.0"
